name: shantika_cubit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  dashed_line: ^0.1.0+3
  carousel_slider: ^5.0.0
  dotted_line: ^3.2.3
  font_awesome_flutter: ^10.8.0
  flutter_widget_from_html: ^0.17.1
  grouped_list: ^6.0.0
  shimmer: ^3.0.0
  flutter_lazy_indexed_stack: ^0.1.0
  with_space_between: ^0.0.2
  table_calendar: ^3.1.0
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  modal_bottom_sheet: ^3.0.0
  webview_flutter: ^4.10.0
  camera: ^0.11.0+2
  photo_view: ^0.15.0

  # Firebase
  firebase_messaging: ^16.0.3
  firebase_crashlytics: ^5.0.3
  firebase_database: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1


  # utilities
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  collection: ^1.18.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  super_tooltip: ^2.0.8
  open_file: ^3.5.3
  file_picker: ^10.3.3
  encrypt: ^5.0.3
  envied: ^1.0.0
  dotted_decoration: ^2.0.0
  device_preview: ^1.2.0
  path_provider: ^2.1.4
  flutter_downloader: ^1.11.8
  equatable: ^2.0.5
  flutter_pdfview: ^1.4.0
  path: ^1.9.0
  jiffy: ^6.3.2



  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

  # Code generation
  json_annotation: ^4.9.0

  # Service locator
  get_it: ^8.0.2

  # User Preference & Local storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1


  # Networking
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.4.1
  awesome_dio_interceptor: ^1.0.0
  socket_io_client: ^3.0.2



  # MAP AND LOCATION
  flutter_map: ^8.1.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  geocode: ^1.0.3
  webview_flutter_wkwebview: ^3.18.4
  envied_generator: ^1.3.1
  uuid: ^4.5.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

  # networking
  retrofit_generator: ^10.0.6

  # env

  # Code generation
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
