// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuLtkyh_1KxnukcdRDcGYbY18sdvNInY',
    appId: '1:140490151417:android:0615141629e4d4b4d39928',
    messagingSenderId: '140490151417',
    projectId: 'garda-a5ea2',
    databaseURL: 'https://garda-a5ea2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garda-a5ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouF31eEAEnJnJyUVSPBnuXGn8yLrfVkY',
    appId: '1:140490151417:ios:a9a277b22046a689d39928',
    messagingSenderId: '140490151417',
    projectId: 'garda-a5ea2',
    databaseURL: 'https://garda-a5ea2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garda-a5ea2.firebasestorage.app',
    iosClientId: '140490151417-99u861ioaqies8n4m4i10gomij3dcdj4.apps.googleusercontent.com',
    iosBundleId: 'id.garda.mobile',
  );
}
